sonar.projectKey=leeeeeoy-portfolio_frontend
sonar.organization=leeeeeoy
sonar.projectName=leeeeeoy-portfolio-frontend

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.dart.lcov.reportPaths=coverage/lcov.info

# 자동 생성 파일 제외 (freezed, json_serializable)
sonar.exclusions=lib/**/*.g.dart,lib/**/*.freezed.dart,lib/asset/**
sonar.coverage.exclusions=lib/**/*.g.dart,lib/**/*.freezed.dart,lib/asset/**,lib/main.dart,lib/firebase_options.dart
