sonar.projectKey=leeeeeoy-portfolio_backend
sonar.organization=leeeeeoy
sonar.projectName=leeeeeoy-portfolio-backend

sonar.sources=src
sonar.tests=src/__tests__
sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPath=tsconfig.json

sonar.exclusions=src/__tests__/**
sonar.test.inclusions=src/__tests__/**
