// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColQMgzPZwIWpEuGmG2grNHCvClavOfT0',
    appId: '1:154525256518:web:c43a6368d9664b7c51f347',
    messagingSenderId: '154525256518',
    projectId: 'leeeeeoy-portfolio',
    authDomain: 'leeeeeoy-portfolio.firebaseapp.com',
    storageBucket: 'leeeeeoy-portfolio.appspot.com',
    measurementId: 'G-4KGWJSMGGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQsfZtPyX45iRZfFtx7sism8r6sBzXyYc',
    appId: '1:154525256518:android:2c2edc8aeb15c5aa51f347',
    messagingSenderId: '154525256518',
    projectId: 'leeeeeoy-portfolio',
    storageBucket: 'leeeeeoy-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXznbb2ZGNhuUBc2E-WeHOQtr_A3RCGuc',
    appId: '1:154525256518:ios:ec121ac5a2e6f80351f347',
    messagingSenderId: '154525256518',
    projectId: 'leeeeeoy-portfolio',
    storageBucket: 'leeeeeoy-portfolio.appspot.com',
    iosBundleId: 'com.example.leeeeeoyPortfolio',
  );
}
